on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Check formatting
        run: zig fmt --check . --exclude zig-pkg --exclude .zig-cache

      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install -y libx11-dev libxrender-dev libxcursor-dev libxrandr-dev libxext-dev

      - name: Run unit tests
        run: zig build test

      - name: Install backend dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt install -y libgl-dev libvulkan-dev libcairo2-dev

      # - name: Build cairo example
      #   working-directory: examples/cairo
      #   run: zig build -fsys=cairo

      - name: Build cursor example
        working-directory: examples/cursor
        run: zig build

      - name: Build embed example
        working-directory: examples/embed
        run: zig build

      - name: Build window example
        working-directory: examples/window
        run: zig build
